title: Cardano
email: cardano@iohk.io
description: SL Documentation
baseurl: ""
url: "https://docs.cardano.iohk.io"
enforce_ssl: docs.cardano.iohk.io
include: ["_pages","_docs"]
permalink: /:title

markdown: kramdown
array: []
