title: Cardano
email: cardano@iohk.io
description: SL Documentation
baseurl: ""
url: "https://cardano-docs.iohk.io"
include: ["_pages","_docs"]
permalink: /:title

#markdown: kramdown
markdown: redcarpet
array: []
